ChildrenScreen: navigation $ icon
1B2K/HealthGuard pull request #105
Opened 2021-05-14 19:29 UTC by HyoukSunKwon

2021-05-14 21:07 UTC, hyunjiLeeTech commented on src/screens/ChildrenScreen.js
> +import AddChildScreen from "./AddChildScreen";
Erase the modules you don't use on this screen. One of the modules you don't use creates an error.
![image](https://user-images.githubusercontent.com/45149474/118330973-1e57be80-b4d6-11eb-8419-b0ee6f0c8a2f.png)

2021-05-14 21:07 UTC, hyunjiLeeTech commented on src/screens/ChildrenScreen.js
> +    marginRight: moderateScale(23),
Use scale for width size/marginRight/marginLeft and verticalScale for height size/marginTop/marginbottom. Please check this and fix it on the other screens you created (EditChildrenScreen)

2021-05-14 21:17 UTC, ElisaNgLi reviewed
For the Children Screen remember to add the Icons for the Birth and Latest like is displayed on the design 
![Screen Shot 2021-05-14 at 5 15 26 PM](https://user-images.githubusercontent.com/43829777/118332480-29135300-b4d8-11eb-968c-832293db503b.png)

2021-05-21 03:35 UTC, hyunjiLeeTech requested changes

2021-05-21 03:35 UTC, hyunjiLeeTech commented on src/screens/ChildrenScreen.js
> +                {/* <Image source={{ uri:u.avatar }} /> */}
Please use TouchableOpacity and make it to navigate to ScheduleScreen when user click a item.

2021-05-21 03:35 UTC, hyunjiLeeTech commented on src/screens/ChildrenScreen.js
> +    width: moderateScale(10),
Add 
resizeMode: "stretch"
You can see code in the file ScheduleScreen as a reference

2021-05-21 03:35 UTC, hyunjiLeeTech commented on src/screens/ChildrenScreen.js
> +    marginBottom: scale(10),
Use scale for width and verticalScale for height (please recheck whole your stylesheet codes). You can recheck the logic of scaling scaling.js file

2021-05-21 03:35 UTC, hyunjiLeeTech commented on src/screens/ChildrenScreen.js
>    },
The start point of name and the icons (schedule and infection icons) should be the same. Currently, it doesn't like the same.

2021-05-21 03:35 UTC, hyunjiLeeTech commented on src/screens/ChildrenScreen.js
> +    margin: scale(5),
Please reduce the distance a little bit so the start end point of the image (profile image) and the end point of the texts (latest) is the same. (In other words, the height of image and the height of name+birth+latest should be the same)

2021-05-29 02:30 UTC, closed without merging