Fix #80 create notification screen
1B2K/HealthGuard pull request #110
Opened 2021-05-18 20:55 UTC by ElisaNgLi

2021-05-19 01:08 UTC, hyunjiLeeTech requested changes

2021-05-19 01:08 UTC, hyunjiLeeTech commented on src/component/Notification/ContentItem.js
> +  render = () => {
Make this component display the list of item (not including status)

2021-05-19 01:08 UTC, hyunjiLeeTech commented on src/screens/NotificationScreen.js
> +    <SafeAreaView style={screenConfig.container}>
Make each status line (upcoming, today and overdue) and make each render funcs filter the items using status (the logic should be changed later. check the status comparing the schedule date and today's device date. We can do it later). You can use ScheduleScreen as a reference.

2021-05-19 01:08 UTC, hyunjiLeeTech commented on src/screens/NotificationScreen.js
> +      </View>
You can handle the case when there is not item in certain section. Need to ask a design for this case to Hena

2021-05-23 00:40 UTC, hyunjiLeeTech requested changes

2021-05-23 00:40 UTC, hyunjiLeeTech commented on src/screens/NotificationScreen.js
> +
Functions named statusToday, statusUpcoming and statusOverdue are duplicates in terms of the logic of function. Make a one function, pass the status to filter the array

2021-05-23 00:40 UTC, hyunjiLeeTech commented on src/screens/NotificationScreen.js
> +    fontSize: moderateScale(12),
If you want to make the size scaling by the height size of phone, use verticalScale. We don't know the logic of moderateScale so using moderateScale makes the design slightly (but obviously need to fix) different depend on what device we test or use until we've got the logic of moderateScale. Check ContentItem.js too

2021-05-23 00:40 UTC, hyunjiLeeTech commented on src/component/Notification/ContentItem.js
> +import colorConfig from "../../config/colors";
Erase the module you don't use on this screen

2021-05-23 09:38 UTC, hyunjiLeeTech commented on src/screens/NotificationScreen.js
> +
When we need to use date to determine the status, we do need 3 separate functions. I delete this. Ignore this review.

2021-06-04 16:19 UTC, HyoukSunKwon approved these changes

2021-06-04 19:17 UTC, hyunjiLeeTech requested changes

2021-06-04 19:17 UTC, hyunjiLeeTech commented on src/screens/NotificationScreen.js
> +  },
Make a icon size little bit smiller and add this
resizeMode: "stretch",

2021-06-04 19:17 UTC, hyunjiLeeTech commented on src/screens/NotificationScreen.js
> +    fontSize: verticalScale(12),
Make a font size bigger for no status text. When you check Hena's design, you can see the font size is slightly bigger than the section font size

2021-06-05 01:00 UTC, hyunjiLeeTech approved these changes

2021-06-05 01:00 UTC, merged